// generated by Fast Light User Interface Designer (fluid) version 1.0110

#include "gettext.h"
#include "KachinaPanel.h"
#include "images.h"
#include "Kachina.h"
#include "support.h"

static void cb_mnuOpen(Fl_Menu_*, void*) {
  openFreqList();
}

static void cb_mnuSave(Fl_Menu_*, void*) {
  saveFreqList();
}

static void cb_mnuExit(Fl_Menu_*, void*) {
  cbExit();
}

static void cb_mnuViewLog(Fl_Menu_*, void*) {
  cbViewLog();
}

static void cb_mnuPreferences(Fl_Menu_*, void*) {
  setDisplayColors();
}

static void cb_mnuAntPorts(Fl_Menu_*, void*) {
  cbmnuAntPorts();
}

static void cb_mnuFreqCal(Fl_Menu_*, void*) {
  openFreqCalibDialog();
}

static void cb_mnuClearAntData(Fl_Menu_*, void*) {
  cbClearAntData();
}

static void cb_mnuNRAMdata(Fl_Menu_*, void*) {
  cbNRAM();
}

static void cb_mnuEvents(Fl_Menu_*, void*) {
  cbEventLog();
}

static void cb_mnuAbout(Fl_Menu_*, void*) {
  about();
}

Fl_Menu_Item menu_[] = {
 {_("&Files"), 0,  0, 0, 64, FL_NORMAL_LABEL, 0, 14, 0},
 {_("&Open"), 0,  (Fl_Callback*)cb_mnuOpen, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {_("&Save"), 0,  (Fl_Callback*)cb_mnuSave, 0, 128, FL_NORMAL_LABEL, 0, 14, 0},
 {_("E&xit"), 0,  (Fl_Callback*)cb_mnuExit, 0, 128, FL_NORMAL_LABEL, 0, 14, 0},
 {_("View Log"), 0,  (Fl_Callback*)cb_mnuViewLog, 0, 2, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0},
 {_("&Config"), 0,  0, 0, 64, FL_NORMAL_LABEL, 0, 14, 0},
 {_("&Display Colors"), 0,  (Fl_Callback*)cb_mnuPreferences, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {_("Antenna Ports"), 0,  (Fl_Callback*)cb_mnuAntPorts, 0, 128, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0},
 {_("Utils"), 0,  0, 0, 64, FL_NORMAL_LABEL, 0, 14, 0},
 {_("&Ant Imped"), 0,  0, 0, 16, FL_NORMAL_LABEL, 0, 14, 0},
 {_("&FreqCal"), 0,  (Fl_Callback*)cb_mnuFreqCal, 0, 128, FL_NORMAL_LABEL, 0, 14, 0},
 {_("Clear Ant\' Data"), 0,  (Fl_Callback*)cb_mnuClearAntData, 0, 128, FL_NORMAL_LABEL, 0, 14, 0},
 {_("&NRAM data"), 0,  (Fl_Callback*)cb_mnuNRAMdata, 0, 128, FL_NORMAL_LABEL, 0, 14, 0},
 {_("Event log"), 0,  (Fl_Callback*)cb_mnuEvents, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0},
 {_("&Help"), 0,  0, 0, 64, FL_NORMAL_LABEL, 0, 14, 0},
 {_("&About"), 0,  (Fl_Callback*)cb_mnuAbout, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0},
 {0,0,0,0,0,0,0,0,0}
};

cFreqControl *FreqDisp=(cFreqControl *)0;

cFreqControl *FreqDispB=(cFreqControl *)0;

Fl_Browser *FreqSelect=(Fl_Browser *)0;

static void cb_FreqSelect(Fl_Browser*, void*) {
  if (FreqSelect->value())
selectFreq();
}

Fl_Choice *vfoSelect=(Fl_Choice *)0;

static void cb_vfoSelect(Fl_Choice*, void*) {
  cbVFOsel();
}

Fl_Button *btnA2B=(Fl_Button *)0;

static void cb_btnA2B(Fl_Button*, void*) {
  cbA2B();
}

Fl_Button *btnAddFreq=(Fl_Button *)0;

static void cb_btnAddFreq(Fl_Button*, void*) {
  addFreq();
}

Fl_Button *btnDelFreq=(Fl_Button *)0;

static void cb_btnDelFreq(Fl_Button*, void*) {
  delFreq();
}

Fl_Button *btnClearList=(Fl_Button *)0;

static void cb_btnClearList(Fl_Button*, void*) {
  clearList();
}

Fl_Wheel_Value_Slider *sldrRIT=(Fl_Wheel_Value_Slider *)0;

static void cb_sldrRIT(Fl_Wheel_Value_Slider*, void*) {
  cbRIT();
}

Fl_Wheel_Value_Slider *sldrVOLUME=(Fl_Wheel_Value_Slider *)0;

static void cb_sldrVOLUME(Fl_Wheel_Value_Slider*, void*) {
  setVolume();
}

Fl_Wheel_Value_Slider *sldrIFSHIFT=(Fl_Wheel_Value_Slider *)0;

static void cb_sldrIFSHIFT(Fl_Wheel_Value_Slider*, void*) {
  setIFshift();
}

Fl_Wheel_Value_Slider *sldrNOTCH=(Fl_Wheel_Value_Slider *)0;

static void cb_sldrNOTCH(Fl_Wheel_Value_Slider*, void*) {
  setNotch();
}

Fl_Value_Slider *sldrDepth=(Fl_Value_Slider *)0;

static void cb_sldrDepth(Fl_Value_Slider*, void*) {
  cbDepth();
}

Fl_Wheel_Value_Slider *sldrNR=(Fl_Wheel_Value_Slider *)0;

static void cb_sldrNR(Fl_Wheel_Value_Slider*, void*) {
  cbNR();
}

Fl_Choice *opMODE=(Fl_Choice *)0;

static void cb_opMODE(Fl_Choice*, void*) {
  setMode();
}

Fl_Choice *opBW=(Fl_Choice *)0;

static void cb_opBW(Fl_Choice*, void*) {
  setBW();
}

Fl_Choice *opNOTCH=(Fl_Choice *)0;

static void cb_opNOTCH(Fl_Choice*, void*) {
  setNotchWidth();
}

Fl_Wheel_Value_Slider *sldrMICGAIN=(Fl_Wheel_Value_Slider *)0;

static void cb_sldrMICGAIN(Fl_Wheel_Value_Slider*, void*) {
  setMicGain();
}

Fl_Wheel_Value_Slider *sldrPOWER=(Fl_Wheel_Value_Slider *)0;

static void cb_sldrPOWER(Fl_Wheel_Value_Slider*, void*) {
  setPower();
}

Fl_Light_Button *btnRIT=(Fl_Light_Button *)0;

static void cb_btnRIT(Fl_Light_Button*, void*) {
  cbbtnRIT();
}

Fl_Light_Button *btnMute=(Fl_Light_Button *)0;

static void cb_btnMute(Fl_Light_Button*, void*) {
  cbMute();
}

Fl_Light_Button *btnIFsh=(Fl_Light_Button *)0;

static void cb_btnIFsh(Fl_Light_Button*, void*) {
  cbIFsh();
}

Fl_Light_Button *btnNotch=(Fl_Light_Button *)0;

static void cb_btnNotch(Fl_Light_Button*, void*) {
  cbbtnNotch();
}

Fl_Light_Button *btnNR=(Fl_Light_Button *)0;

static void cb_btnNR(Fl_Light_Button*, void*) {
  cbbtnNR();
}

Fl_Light_Button *btnAttenuator=(Fl_Light_Button *)0;

static void cb_btnAttenuator(Fl_Light_Button*, void*) {
  cbAttenuator();
}

Fl_Light_Button *btnPreamp=(Fl_Light_Button *)0;

static void cb_btnPreamp(Fl_Light_Button*, void*) {
  cbPreamp();
}

Fl_Group *grpMeters1=(Fl_Group *)0;

Fl_Button *btnSmeter=(Fl_Button *)0;

static void cb_btnSmeter(Fl_Button*, void*) {
  cbSmeter();
}

Fl_SigBar *sldrRcvSignal=(Fl_SigBar *)0;

Fl_Slider *sldrSQ=(Fl_Slider *)0;

Fl_Box *boxSquelch=(Fl_Box *)0;

Fl_Group *grpMeters2=(Fl_Group *)0;

Fl_Button *btnPower=(Fl_Button *)0;

static void cb_btnPower(Fl_Button*, void*) {
  cbPWR();
}

Fl_SigBar *sldrFwdPwr=(Fl_SigBar *)0;

Fl_SigBar *sldrRefPwr=(Fl_SigBar *)0;

Fl_Button *btnSWR=(Fl_Button *)0;

static void cb_btnSWR(Fl_Button*, void*) {
  cbSWR();
}

Fl_Button *btn_show_controls=(Fl_Button *)0;

static void cb_btn_show_controls(Fl_Button*, void*) {
  show_controls();
}

Fl_Light_Button *btnPTT=(Fl_Light_Button *)0;

static void cb_btnPTT(Fl_Light_Button*, void*) {
  cbPTT();
}

Fl_Light_Button *btnTune=(Fl_Light_Button *)0;

static void cb_btnTune(Fl_Light_Button*, void*) {
  cbTune();
}

Fl_Light_Button *btnCarrier=(Fl_Light_Button *)0;

static void cb_btnCarrier(Fl_Light_Button*, void*) {
  cbCarrier();
}

Fl_Choice *antSelect=(Fl_Choice *)0;

static void cb_antSelect(Fl_Choice*, void*) {
  cbAntSel();
}

Fl_Output *txtTEMP=(Fl_Output *)0;

static void cb_txtTEMP(Fl_Output*, void*) {
  cbTemp();
}

Fl_Tabs *tabs=(Fl_Tabs *)0;

Fl_Group *CWtab=(Fl_Group *)0;

Fl_Light_Button *btnSPOT=(Fl_Light_Button *)0;

static void cb_btnSPOT(Fl_Light_Button*, void*) {
  cbSPOT();
}

Fl_Counter *cntrWPM=(Fl_Counter *)0;

static void cb_cntrWPM(Fl_Counter*, void*) {
  cbWPM();
}

Fl_Counter *sldrCWweight=(Fl_Counter *)0;

static void cb_sldrCWweight(Fl_Counter*, void*) {
  cbCWweight();
}

Fl_Counter *sldrCWattack=(Fl_Counter *)0;

static void cb_sldrCWattack(Fl_Counter*, void*) {
  cbCWattack();
}

Fl_Choice *mnuCWmode=(Fl_Choice *)0;

static void cb_mnuCWmode(Fl_Choice*, void*) {
  cbCWmode();
}

Fl_Check_Button *btnQSKonoff=(Fl_Check_Button *)0;

static void cb_btnQSKonoff(Fl_Check_Button*, void*) {
  cbQSKonoff();
}

Fl_Group *CW2tab=(Fl_Group *)0;

Fl_Counter *sldrSideTone=(Fl_Counter *)0;

static void cb_sldrSideTone(Fl_Counter*, void*) {
  cbSidetone();
}

Fl_Choice *mnuCWoffset=(Fl_Choice *)0;

static void cb_mnuCWoffset(Fl_Choice*, void*) {
  cbCWoffset();
}

Fl_Choice *mnuCWdefFilter=(Fl_Choice *)0;

static void cb_mnuCWdefFilter(Fl_Choice*, void*) {
  cbCWdefFilter();
}

Fl_Group *VOXtab=(Fl_Group *)0;

Fl_Counter *sldrVoxLevel=(Fl_Counter *)0;

static void cb_sldrVoxLevel(Fl_Counter*, void*) {
  cbsldrVoxLevel();
}

Fl_Counter *sldrAntiVox=(Fl_Counter *)0;

static void cb_sldrAntiVox(Fl_Counter*, void*) {
  cbsldrAntiVox();
}

Fl_Counter *sldrVoxDelay=(Fl_Counter *)0;

static void cb_sldrVoxDelay(Fl_Counter*, void*) {
  cbsldrVoxDelay();
}

Fl_Light_Button *btnVoxOnOff=(Fl_Light_Button *)0;

static void cb_btnVoxOnOff(Fl_Light_Button*, void*) {
  cbVoxOnOff();
}

Fl_Group *SPCHtab=(Fl_Group *)0;

Fl_Counter *MonVol=(Fl_Counter *)0;

Fl_Light_Button *btnSpchMon=(Fl_Light_Button *)0;

static void cb_btnSpchMon(Fl_Light_Button*, void*) {
  cbSpchMon();
}

Fl_Counter *sldrCompression=(Fl_Counter *)0;

static void cb_sldrCompression(Fl_Counter*, void*) {
  cbsldrCompression();
}

Fl_Light_Button *btnSpchProc=(Fl_Light_Button *)0;

static void cb_btnSpchProc(Fl_Light_Button*, void*) {
  cbbtnSpchProc();
}

Fl_Group *RXtab=(Fl_Group *)0;

Fl_Counter *sldrSqlLevel=(Fl_Counter *)0;

static void cb_sldrSqlLevel(Fl_Counter*, void*) {
  cbSqlLevel();
}

static void cb_btnSQLtype(Fl_Round_Button*, void*) {
  btnSQLtype[1]->value(0);
cbSQLtype();
}

Fl_Counter *sldrAgcAction=(Fl_Counter *)0;

static void cb_sldrAgcAction(Fl_Counter*, void*) {
  cbsldrAgcAction();
}

Fl_Counter *sldrAgcSpeed=(Fl_Counter *)0;

static void cb_sldrAgcSpeed(Fl_Counter*, void*) {
  cbsldrAgcSpeed();
}

Fl_Round_Button *btnSQLtype[2]={(Fl_Round_Button *)0};

static void cb_btnSQLtype1(Fl_Round_Button*, void*) {
  btnSQLtype[0]->value(0);
cbSQLtype();
}

Fl_Group *TXtab=(Fl_Group *)0;

Fl_Check_Button *btnAmpOnOff=(Fl_Check_Button *)0;

static void cb_btnAmpOnOff(Fl_Check_Button*, void*) {
  cbbtnAmpOnOff();
}

Fl_Check_Button *tuner_bypass=(Fl_Check_Button *)0;

Fl_Counter *sldrXmtEqualizer=(Fl_Counter *)0;

static void cb_sldrXmtEqualizer(Fl_Counter*, void*) {
  cbsldrXmtEqualizer();
}

Fl_Group *OSCtab=(Fl_Group *)0;

Fl_Counter *ctr_vfo_adj=(Fl_Counter *)0;

static void cb_ctr_vfo_adj(Fl_Counter*, void*) {
  cb_vfo_adj();
}

Fl_Double_Window* Kachina_window() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(500, 355, _("kcat"));
    w = o;
    o->color((Fl_Color)51);
    { Fl_Menu_Bar* o = new Fl_Menu_Bar(2, 2, 349, 22);
      o->labelsize(12);
      o->textsize(12);
      o->menu(menu_);
    } // Fl_Menu_Bar* o
    { cFreqControl* o = FreqDisp = new cFreqControl(2, 25, 174, 40, _("8"));
      FreqDisp->tooltip(_("Set Frequency"));
      FreqDisp->box(FL_DOWN_BOX);
      FreqDisp->color((Fl_Color)FL_BACKGROUND_COLOR);
      FreqDisp->selection_color((Fl_Color)FL_BACKGROUND_COLOR);
      FreqDisp->labeltype(FL_NORMAL_LABEL);
      FreqDisp->labelfont(0);
      FreqDisp->labelsize(14);
      FreqDisp->labelcolor((Fl_Color)FL_FOREGROUND_COLOR);
      FreqDisp->align(FL_ALIGN_CENTER);
      FreqDisp->when(FL_WHEN_RELEASE);
      o->SetONOFFCOLOR (FL_YELLOW, FL_BLACK);
      o->setCallBack(movFreq);
    } // cFreqControl* FreqDisp
    { cFreqControl* o = FreqDispB = new cFreqControl(177, 25, 174, 40, _("8"));
      FreqDispB->tooltip(_("Set Frequency"));
      FreqDispB->box(FL_DOWN_BOX);
      FreqDispB->color((Fl_Color)FL_BACKGROUND_COLOR);
      FreqDispB->selection_color((Fl_Color)FL_BACKGROUND_COLOR);
      FreqDispB->labeltype(FL_NORMAL_LABEL);
      FreqDispB->labelfont(0);
      FreqDispB->labelsize(14);
      FreqDispB->labelcolor((Fl_Color)FL_FOREGROUND_COLOR);
      FreqDispB->align(FL_ALIGN_CENTER);
      FreqDispB->when(FL_WHEN_RELEASE);
      o->SetONOFFCOLOR (FL_YELLOW, FL_BLACK);
      o->setCallBack(movFreqB);
    } // cFreqControl* FreqDispB
    { Fl_Box* o = new Fl_Box(2, 68, 60, 20, _("vfo A"));
      o->box(FL_FLAT_BOX);
      o->color((Fl_Color)51);
      o->align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
    } // Fl_Box* o
    { Fl_Box* o = new Fl_Box(177, 68, 60, 20, _("vfo B"));
      o->box(FL_FLAT_BOX);
      o->color((Fl_Color)51);
      o->align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
    } // Fl_Box* o
    { FreqSelect = new Fl_Browser(352, 2, 146, 63);
      FreqSelect->tooltip(_("Select operating frequency/mode"));
      FreqSelect->type(2);
      FreqSelect->labelfont(4);
      FreqSelect->labelsize(12);
      FreqSelect->textfont(13);
      FreqSelect->textsize(12);
      FreqSelect->callback((Fl_Callback*)cb_FreqSelect);
    } // Fl_Browser* FreqSelect
    { Fl_Choice* o = vfoSelect = new Fl_Choice(48, 68, 100, 20);
      vfoSelect->box(FL_DOWN_BOX);
      vfoSelect->down_box(FL_BORDER_BOX);
      vfoSelect->color((Fl_Color)FL_LIGHT1);
      vfoSelect->callback((Fl_Callback*)cb_vfoSelect);
      o->add("Rx-A Tx-A|Rx-B Tx-B|Rx-A Tx-B|Rx-B Tx-A");
      o->value(0);
    } // Fl_Choice* vfoSelect
    { btnA2B = new Fl_Button(241, 68, 55, 20, _("A -> B"));
      btnA2B->tooltip(_("Active -> Inactive"));
      btnA2B->callback((Fl_Callback*)cb_btnA2B);
    } // Fl_Button* btnA2B
    { btnAddFreq = new Fl_Button(351, 68, 20, 20, _("@|>"));
      btnAddFreq->tooltip(_("Add to list"));
      btnAddFreq->box(FL_PLASTIC_UP_BOX);
      btnAddFreq->labelsize(10);
      btnAddFreq->callback((Fl_Callback*)cb_btnAddFreq);
    } // Fl_Button* btnAddFreq
    { btnDelFreq = new Fl_Button(372, 68, 18, 20, _("@1+"));
      btnDelFreq->tooltip(_("Delete from list"));
      btnDelFreq->box(FL_PLASTIC_UP_BOX);
      btnDelFreq->labelsize(10);
      btnDelFreq->callback((Fl_Callback*)cb_btnDelFreq);
    } // Fl_Button* btnDelFreq
    { btnClearList = new Fl_Button(391, 68, 20, 20, _("@-1square"));
      btnClearList->tooltip(_("Clear list"));
      btnClearList->box(FL_PLASTIC_UP_BOX);
      btnClearList->labelsize(10);
      btnClearList->callback((Fl_Callback*)cb_btnClearList);
    } // Fl_Button* btnClearList
    { sldrRIT = new Fl_Wheel_Value_Slider(2, 90, 346, 18);
      sldrRIT->tooltip(_("RIT (-790 to 790 Hz)"));
      sldrRIT->type(5);
      sldrRIT->box(FL_DOWN_BOX);
      sldrRIT->color((Fl_Color)26);
      sldrRIT->selection_color((Fl_Color)FL_BACKGROUND_COLOR);
      sldrRIT->labeltype(FL_NO_LABEL);
      sldrRIT->labelfont(0);
      sldrRIT->labelsize(14);
      sldrRIT->labelcolor((Fl_Color)FL_FOREGROUND_COLOR);
      sldrRIT->minimum(-790);
      sldrRIT->maximum(790);
      sldrRIT->step(10);
      sldrRIT->textsize(14);
      sldrRIT->callback((Fl_Callback*)cb_sldrRIT);
      sldrRIT->align(FL_ALIGN_RIGHT);
      sldrRIT->when(FL_WHEN_CHANGED);
    } // Fl_Wheel_Value_Slider* sldrRIT
    { sldrVOLUME = new Fl_Wheel_Value_Slider(2, 111, 346, 18, _("Audio Volume"));
      sldrVOLUME->tooltip(_("Audio output volume"));
      sldrVOLUME->type(5);
      sldrVOLUME->box(FL_DOWN_BOX);
      sldrVOLUME->color((Fl_Color)26);
      sldrVOLUME->selection_color((Fl_Color)FL_BACKGROUND_COLOR);
      sldrVOLUME->labeltype(FL_NO_LABEL);
      sldrVOLUME->labelfont(0);
      sldrVOLUME->labelsize(14);
      sldrVOLUME->labelcolor((Fl_Color)FL_FOREGROUND_COLOR);
      sldrVOLUME->value(0.2);
      sldrVOLUME->textsize(14);
      sldrVOLUME->callback((Fl_Callback*)cb_sldrVOLUME);
      sldrVOLUME->align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
      sldrVOLUME->when(FL_WHEN_CHANGED);
    } // Fl_Wheel_Value_Slider* sldrVOLUME
    { sldrIFSHIFT = new Fl_Wheel_Value_Slider(2, 132, 346, 18);
      sldrIFSHIFT->tooltip(_("Set IF Shift Frequency"));
      sldrIFSHIFT->type(5);
      sldrIFSHIFT->box(FL_DOWN_BOX);
      sldrIFSHIFT->color((Fl_Color)26);
      sldrIFSHIFT->selection_color((Fl_Color)FL_BACKGROUND_COLOR);
      sldrIFSHIFT->labeltype(FL_NO_LABEL);
      sldrIFSHIFT->labelfont(0);
      sldrIFSHIFT->labelsize(14);
      sldrIFSHIFT->labelcolor((Fl_Color)FL_FOREGROUND_COLOR);
      sldrIFSHIFT->minimum(-1280);
      sldrIFSHIFT->maximum(1270);
      sldrIFSHIFT->step(10);
      sldrIFSHIFT->textsize(14);
      sldrIFSHIFT->callback((Fl_Callback*)cb_sldrIFSHIFT);
      sldrIFSHIFT->align(FL_ALIGN_CENTER|FL_ALIGN_INSIDE);
      sldrIFSHIFT->when(FL_WHEN_CHANGED);
    } // Fl_Wheel_Value_Slider* sldrIFSHIFT
    { sldrNOTCH = new Fl_Wheel_Value_Slider(2, 152, 346, 18);
      sldrNOTCH->tooltip(_("Set Notch Frequency"));
      sldrNOTCH->type(5);
      sldrNOTCH->box(FL_DOWN_BOX);
      sldrNOTCH->color((Fl_Color)26);
      sldrNOTCH->selection_color((Fl_Color)FL_BACKGROUND_COLOR);
      sldrNOTCH->labeltype(FL_NO_LABEL);
      sldrNOTCH->labelfont(0);
      sldrNOTCH->labelsize(14);
      sldrNOTCH->labelcolor((Fl_Color)FL_FOREGROUND_COLOR);
      sldrNOTCH->minimum(200);
      sldrNOTCH->maximum(2750);
      sldrNOTCH->step(10);
      sldrNOTCH->textsize(14);
      sldrNOTCH->callback((Fl_Callback*)cb_sldrNOTCH);
      sldrNOTCH->align(FL_ALIGN_CENTER);
      sldrNOTCH->when(FL_WHEN_CHANGED);
    } // Fl_Wheel_Value_Slider* sldrNOTCH
    { sldrDepth = new Fl_Value_Slider(2, 152, 295, 18);
      sldrDepth->tooltip(_("Set Notch Depth"));
      sldrDepth->type(5);
      sldrDepth->color((Fl_Color)26);
      sldrDepth->labeltype(FL_NO_LABEL);
      sldrDepth->maximum(100);
      sldrDepth->step(1);
      sldrDepth->value(50);
      sldrDepth->textsize(14);
      sldrDepth->callback((Fl_Callback*)cb_sldrDepth);
      sldrDepth->align(FL_ALIGN_CENTER);
      sldrDepth->hide();
    } // Fl_Value_Slider* sldrDepth
    { sldrNR = new Fl_Wheel_Value_Slider(2, 173, 346, 18);
      sldrNR->tooltip(_("Noise Reduction (min -> max)"));
      sldrNR->type(5);
      sldrNR->box(FL_DOWN_BOX);
      sldrNR->color((Fl_Color)26);
      sldrNR->selection_color((Fl_Color)FL_BACKGROUND_COLOR);
      sldrNR->labeltype(FL_NO_LABEL);
      sldrNR->labelfont(0);
      sldrNR->labelsize(14);
      sldrNR->labelcolor((Fl_Color)FL_FOREGROUND_COLOR);
      sldrNR->maximum(255);
      sldrNR->step(1);
      sldrNR->textsize(14);
      sldrNR->callback((Fl_Callback*)cb_sldrNR);
      sldrNR->align(FL_ALIGN_RIGHT);
      sldrNR->when(FL_WHEN_CHANGED);
    } // Fl_Wheel_Value_Slider* sldrNR
    { opMODE = new Fl_Choice(2, 194, 70, 20);
      opMODE->tooltip(_("Select Mode"));
      opMODE->down_box(FL_BORDER_BOX);
      opMODE->callback((Fl_Callback*)cb_opMODE);
    } // Fl_Choice* opMODE
    { opBW = new Fl_Choice(78, 194, 70, 20);
      opBW->tooltip(_("Select Bandwidth"));
      opBW->down_box(FL_BORDER_BOX);
      opBW->callback((Fl_Callback*)cb_opBW);
    } // Fl_Choice* opBW
    { opNOTCH = new Fl_Choice(154, 194, 71, 20);
      opNOTCH->tooltip(_("Select Notch Depth"));
      opNOTCH->down_box(FL_BORDER_BOX);
      opNOTCH->callback((Fl_Callback*)cb_opNOTCH);
    } // Fl_Choice* opNOTCH
    { sldrMICGAIN = new Fl_Wheel_Value_Slider(2, 216, 346, 18, _("Mic"));
      sldrMICGAIN->tooltip(_("Mic / Gain control"));
      sldrMICGAIN->type(5);
      sldrMICGAIN->box(FL_DOWN_BOX);
      sldrMICGAIN->color((Fl_Color)26);
      sldrMICGAIN->selection_color((Fl_Color)FL_BACKGROUND_COLOR);
      sldrMICGAIN->labeltype(FL_NORMAL_LABEL);
      sldrMICGAIN->labelfont(0);
      sldrMICGAIN->labelsize(14);
      sldrMICGAIN->labelcolor((Fl_Color)FL_FOREGROUND_COLOR);
      sldrMICGAIN->textsize(14);
      sldrMICGAIN->callback((Fl_Callback*)cb_sldrMICGAIN);
      sldrMICGAIN->align(FL_ALIGN_RIGHT);
      sldrMICGAIN->when(FL_WHEN_CHANGED);
    } // Fl_Wheel_Value_Slider* sldrMICGAIN
    { sldrPOWER = new Fl_Wheel_Value_Slider(2, 237, 346, 18, _("Pwr"));
      sldrPOWER->tooltip(_("Set Power Output"));
      sldrPOWER->type(5);
      sldrPOWER->box(FL_DOWN_BOX);
      sldrPOWER->color((Fl_Color)26);
      sldrPOWER->selection_color((Fl_Color)FL_BACKGROUND_COLOR);
      sldrPOWER->labeltype(FL_NORMAL_LABEL);
      sldrPOWER->labelfont(0);
      sldrPOWER->labelsize(14);
      sldrPOWER->labelcolor((Fl_Color)FL_FOREGROUND_COLOR);
      sldrPOWER->maximum(100);
      sldrPOWER->step(1);
      sldrPOWER->value(20);
      sldrPOWER->textsize(14);
      sldrPOWER->callback((Fl_Callback*)cb_sldrPOWER);
      sldrPOWER->align(FL_ALIGN_RIGHT);
      sldrPOWER->when(FL_WHEN_CHANGED);
    } // Fl_Wheel_Value_Slider* sldrPOWER
    { btnRIT = new Fl_Light_Button(351, 90, 60, 18, _("RIT"));
      btnRIT->tooltip(_("RIT on/off"));
      btnRIT->callback((Fl_Callback*)cb_btnRIT);
    } // Fl_Light_Button* btnRIT
    { btnMute = new Fl_Light_Button(351, 111, 60, 18, _("mute"));
      btnMute->tooltip(_("Speaker Mute on/off"));
      btnMute->callback((Fl_Callback*)cb_btnMute);
    } // Fl_Light_Button* btnMute
    { btnIFsh = new Fl_Light_Button(351, 132, 60, 18, _("IFsh"));
      btnIFsh->tooltip(_("IF Shift On/Off"));
      btnIFsh->callback((Fl_Callback*)cb_btnIFsh);
    } // Fl_Light_Button* btnIFsh
    { btnNotch = new Fl_Light_Button(351, 152, 60, 18, _("Ntch"));
      btnNotch->tooltip(_("Notch - Manual (off) Auto (on)"));
      btnNotch->callback((Fl_Callback*)cb_btnNotch);
    } // Fl_Light_Button* btnNotch
    { btnNR = new Fl_Light_Button(351, 173, 60, 18, _("NR"));
      btnNR->tooltip(_("NR on/off"));
      btnNR->callback((Fl_Callback*)cb_btnNR);
    } // Fl_Light_Button* btnNR
    { btnAttenuator = new Fl_Light_Button(235, 194, 53, 20, _("Att"));
      btnAttenuator->tooltip(_("Attenuator On/Off"));
      btnAttenuator->callback((Fl_Callback*)cb_btnAttenuator);
    } // Fl_Light_Button* btnAttenuator
    { btnPreamp = new Fl_Light_Button(351, 194, 60, 20, _("Pre"));
      btnPreamp->tooltip(_("Preamp On/Off"));
      btnPreamp->callback((Fl_Callback*)cb_btnPreamp);
    } // Fl_Light_Button* btnPreamp
    { grpMeters1 = new Fl_Group(413, 68, 84, 210);
      grpMeters1->box(FL_THIN_DOWN_BOX);
      grpMeters1->color((Fl_Color)FL_GRAY0);
      grpMeters1->selection_color((Fl_Color)FL_LIGHT2);
      grpMeters1->align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
      { Fl_Button* o = btnSmeter = new Fl_Button(421, 73, 40, 200);
        btnSmeter->tooltip(_("Click - change scale"));
        btnSmeter->box(FL_FLAT_BOX);
        btnSmeter->down_box(FL_FLAT_BOX);
        btnSmeter->color((Fl_Color)48);
        btnSmeter->selection_color((Fl_Color)48);
        btnSmeter->callback((Fl_Callback*)cb_btnSmeter);
        btnSmeter->align(FL_ALIGN_CENTER|FL_ALIGN_INSIDE);
        o->image(image_smeter);
      } // Fl_Button* btnSmeter
      { Fl_SigBar* o = sldrRcvSignal = new Fl_SigBar(464, 82, 10, 182);
        sldrRcvSignal->box(FL_FLAT_BOX);
        sldrRcvSignal->color((Fl_Color)10);
        sldrRcvSignal->selection_color((Fl_Color)2);
        sldrRcvSignal->labeltype(FL_NORMAL_LABEL);
        sldrRcvSignal->labelfont(0);
        sldrRcvSignal->labelsize(14);
        sldrRcvSignal->labelcolor((Fl_Color)FL_FOREGROUND_COLOR);
        sldrRcvSignal->align(FL_ALIGN_CENTER);
        sldrRcvSignal->when(FL_WHEN_RELEASE);
        o->minimum(0.0f);
        o->maximum(-128.0f);
        o->horizontal(false);
      } // Fl_SigBar* sldrRcvSignal
      { sldrSQ = new Fl_Slider(477, 82, 12, 182);
        sldrSQ->box(FL_FLAT_BOX);
        sldrSQ->color((Fl_Color)FL_FOREGROUND_COLOR);
        sldrSQ->selection_color((Fl_Color)3);
        sldrSQ->labeltype(FL_NO_LABEL);
        sldrSQ->labelcolor((Fl_Color)3);
        sldrSQ->maximum(-127);
        sldrSQ->step(1);
        sldrSQ->value(-100);
        sldrSQ->deactivate();
      } // Fl_Slider* sldrSQ
      { boxSquelch = new Fl_Box(478, 71, 9, 9);
        boxSquelch->box(FL_OVAL_BOX);
        boxSquelch->color((Fl_Color)6);
        boxSquelch->selection_color((Fl_Color)FL_FOREGROUND_COLOR);
      } // Fl_Box* boxSquelch
      grpMeters1->end();
    } // Fl_Group* grpMeters1
    { grpMeters2 = new Fl_Group(413, 68, 84, 210);
      grpMeters2->box(FL_THIN_DOWN_BOX);
      grpMeters2->color((Fl_Color)FL_FOREGROUND_COLOR);
      grpMeters2->selection_color((Fl_Color)FL_LIGHT2);
      grpMeters2->align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
      grpMeters2->hide();
      { Fl_Button* o = btnPower = new Fl_Button(416, 73, 26, 200);
        btnPower->tooltip(_("Click - FWD / ALC"));
        btnPower->box(FL_FLAT_BOX);
        btnPower->down_box(FL_FLAT_BOX);
        btnPower->color((Fl_Color)48);
        btnPower->selection_color((Fl_Color)48);
        btnPower->callback((Fl_Callback*)cb_btnPower);
        btnPower->align(FL_ALIGN_CENTER|FL_ALIGN_INSIDE);
        o->image(image_p150);
      } // Fl_Button* btnPower
      { Fl_SigBar* o = sldrFwdPwr = new Fl_SigBar(443, 82, 11, 182);
        sldrFwdPwr->box(FL_FLAT_BOX);
        sldrFwdPwr->color((Fl_Color)14);
        sldrFwdPwr->selection_color((Fl_Color)6);
        sldrFwdPwr->labeltype(FL_NORMAL_LABEL);
        sldrFwdPwr->labelfont(0);
        sldrFwdPwr->labelsize(14);
        sldrFwdPwr->labelcolor((Fl_Color)FL_FOREGROUND_COLOR);
        sldrFwdPwr->align(FL_ALIGN_CENTER);
        sldrFwdPwr->when(FL_WHEN_RELEASE);
        o->minimum(120.0f);
        o->maximum(0.0f);
        o->horizontal(false);
      } // Fl_SigBar* sldrFwdPwr
      { Fl_SigBar* o = sldrRefPwr = new Fl_SigBar(456, 82, 10, 182);
        sldrRefPwr->box(FL_FLAT_BOX);
        sldrRefPwr->color((Fl_Color)9);
        sldrRefPwr->selection_color((Fl_Color)1);
        sldrRefPwr->labeltype(FL_NORMAL_LABEL);
        sldrRefPwr->labelfont(0);
        sldrRefPwr->labelsize(14);
        sldrRefPwr->labelcolor((Fl_Color)FL_FOREGROUND_COLOR);
        sldrRefPwr->align(FL_ALIGN_CENTER);
        sldrRefPwr->when(FL_WHEN_RELEASE);
        o->minimum(50.0f);
        o->maximum(0.0f);
        o->horizontal(false);
      } // Fl_SigBar* sldrRefPwr
      { Fl_Button* o = btnSWR = new Fl_Button(468, 73, 26, 200);
        btnSWR->tooltip(_("Click REF / SWR"));
        btnSWR->box(FL_FLAT_BOX);
        btnSWR->down_box(FL_FLAT_BOX);
        btnSWR->color((Fl_Color)48);
        btnSWR->selection_color((Fl_Color)48);
        btnSWR->callback((Fl_Callback*)cb_btnSWR);
        btnSWR->align(FL_ALIGN_CENTER|FL_ALIGN_INSIDE);
        o->image(image_swr);
      } // Fl_Button* btnSWR
      grpMeters2->end();
    } // Fl_Group* grpMeters2
    { btn_show_controls = new Fl_Button(2, 258, 18, 20, _("@-22->"));
      btn_show_controls->tooltip(_("Show/Hide controls"));
      btn_show_controls->callback((Fl_Callback*)cb_btn_show_controls);
    } // Fl_Button* btn_show_controls
    { btnPTT = new Fl_Light_Button(24, 258, 64, 20, _("PTT"));
      btnPTT->tooltip(_("Xmt On/Off"));
      btnPTT->callback((Fl_Callback*)cb_btnPTT);
    } // Fl_Light_Button* btnPTT
    { btnTune = new Fl_Light_Button(92, 258, 64, 20, _("Tune"));
      btnTune->tooltip(_("Auto-tune Antenna"));
      btnTune->type(0);
      btnTune->callback((Fl_Callback*)cb_btnTune);
    } // Fl_Light_Button* btnTune
    { btnCarrier = new Fl_Light_Button(161, 258, 64, 20, _("Carr"));
      btnCarrier->tooltip(_("Constant Carrier"));
      btnCarrier->callback((Fl_Callback*)cb_btnCarrier);
    } // Fl_Light_Button* btnCarrier
    { Fl_Choice* o = antSelect = new Fl_Choice(228, 258, 120, 20);
      antSelect->down_box(FL_BORDER_BOX);
      antSelect->callback((Fl_Callback*)cb_antSelect);
      o->add("Ant: table|Ant: A-A|Ant: A-B|Ant: B-A|Ant: B-B");
      o->value(0);
    } // Fl_Choice* antSelect
    { txtTEMP = new Fl_Output(351, 258, 40, 20, _("C"));
      txtTEMP->tooltip(_("Click C / F"));
      txtTEMP->color((Fl_Color)FL_FOREGROUND_COLOR);
      txtTEMP->selection_color((Fl_Color)FL_BACKGROUND2_COLOR);
      txtTEMP->labelfont(13);
      txtTEMP->textfont(13);
      txtTEMP->textcolor((Fl_Color)62);
      txtTEMP->callback((Fl_Callback*)cb_txtTEMP);
      txtTEMP->align(FL_ALIGN_RIGHT);
    } // Fl_Output* txtTEMP
    { tabs = new Fl_Tabs(1, 282, 497, 70);
      tabs->selection_color((Fl_Color)FL_LIGHT1);
      { CWtab = new Fl_Group(2, 302, 495, 50, _("CW"));
        CWtab->color((Fl_Color)FL_LIGHT1);
        CWtab->selection_color((Fl_Color)FL_LIGHT1);
        { btnSPOT = new Fl_Light_Button(10, 310, 64, 22, _("Spot"));
          btnSPOT->callback((Fl_Callback*)cb_btnSPOT);
        } // Fl_Light_Button* btnSPOT
        { cntrWPM = new Fl_Counter(92, 310, 60, 22, _("Wpm"));
          cntrWPM->type(1);
          cntrWPM->minimum(5);
          cntrWPM->maximum(80);
          cntrWPM->step(1);
          cntrWPM->value(18);
          cntrWPM->callback((Fl_Callback*)cb_cntrWPM);
        } // Fl_Counter* cntrWPM
        { sldrCWweight = new Fl_Counter(174, 310, 60, 22, _("Weight"));
          sldrCWweight->type(1);
          sldrCWweight->minimum(0.75);
          sldrCWweight->maximum(1.5);
          sldrCWweight->step(0.05);
          sldrCWweight->value(1);
          sldrCWweight->callback((Fl_Callback*)cb_sldrCWweight);
        } // Fl_Counter* sldrCWweight
        { sldrCWattack = new Fl_Counter(256, 310, 60, 22, _("Attack"));
          sldrCWattack->tooltip(_("QSK delay (msec)"));
          sldrCWattack->type(1);
          sldrCWattack->minimum(0);
          sldrCWattack->maximum(255);
          sldrCWattack->step(1);
          sldrCWattack->value(127);
          sldrCWattack->callback((Fl_Callback*)cb_sldrCWattack);
        } // Fl_Counter* sldrCWattack
        { Fl_Choice* o = mnuCWmode = new Fl_Choice(338, 310, 65, 22, _("Mode"));
          mnuCWmode->down_box(FL_BORDER_BOX);
          mnuCWmode->callback((Fl_Callback*)cb_mnuCWmode);
          mnuCWmode->align(FL_ALIGN_BOTTOM);
          o->add("Left|Right|Str't");
          o->value(1);
        } // Fl_Choice* mnuCWmode
        { btnQSKonoff = new Fl_Check_Button(426, 310, 54, 18, _("QSK"));
          btnQSKonoff->tooltip(_("Enable keyer"));
          btnQSKonoff->down_box(FL_DOWN_BOX);
          btnQSKonoff->callback((Fl_Callback*)cb_btnQSKonoff);
        } // Fl_Check_Button* btnQSKonoff
        CWtab->end();
      } // Fl_Group* CWtab
      { CW2tab = new Fl_Group(2, 302, 495, 50, _("CW -xtra"));
        CW2tab->color((Fl_Color)FL_LIGHT1);
        CW2tab->selection_color((Fl_Color)FL_LIGHT1);
        CW2tab->hide();
        { sldrSideTone = new Fl_Counter(88, 310, 60, 22, _("S-T vol"));
          sldrSideTone->tooltip(_("Side tone volume"));
          sldrSideTone->type(1);
          sldrSideTone->minimum(0);
          sldrSideTone->maximum(100);
          sldrSideTone->step(1);
          sldrSideTone->value(24);
          sldrSideTone->callback((Fl_Callback*)cb_sldrSideTone);
        } // Fl_Counter* sldrSideTone
        { Fl_Choice* o = mnuCWoffset = new Fl_Choice(200, 310, 65, 22, _("Offset"));
          mnuCWoffset->down_box(FL_BORDER_BOX);
          mnuCWoffset->callback((Fl_Callback*)cb_mnuCWoffset);
          mnuCWoffset->align(FL_ALIGN_BOTTOM);
          o->add("300|400|500|600|700|800");
          o->value(4);
        } // Fl_Choice* mnuCWoffset
        { Fl_Choice* o = mnuCWdefFilter = new Fl_Choice(318, 310, 65, 22, _("Def\' Filt\'"));
          mnuCWdefFilter->down_box(FL_BORDER_BOX);
          mnuCWdefFilter->callback((Fl_Callback*)cb_mnuCWdefFilter);
          mnuCWdefFilter->align(FL_ALIGN_BOTTOM);
          o->add("Wide|Narr");
          o->value(1);
        } // Fl_Choice* mnuCWdefFilter
        CW2tab->end();
      } // Fl_Group* CW2tab
      { VOXtab = new Fl_Group(2, 302, 495, 50, _("Vox"));
        VOXtab->hide();
        { sldrVoxLevel = new Fl_Counter(60, 310, 70, 22, _("gain"));
          sldrVoxLevel->type(1);
          sldrVoxLevel->minimum(0);
          sldrVoxLevel->maximum(255);
          sldrVoxLevel->step(1);
          sldrVoxLevel->callback((Fl_Callback*)cb_sldrVoxLevel);
        } // Fl_Counter* sldrVoxLevel
        { sldrAntiVox = new Fl_Counter(164, 310, 70, 22, _("anti"));
          sldrAntiVox->type(1);
          sldrAntiVox->minimum(0);
          sldrAntiVox->maximum(255);
          sldrAntiVox->step(1);
          sldrAntiVox->callback((Fl_Callback*)cb_sldrAntiVox);
        } // Fl_Counter* sldrAntiVox
        { sldrVoxDelay = new Fl_Counter(268, 310, 70, 22, _("delay"));
          sldrVoxDelay->type(1);
          sldrVoxDelay->minimum(0);
          sldrVoxDelay->maximum(100);
          sldrVoxDelay->step(1);
          sldrVoxDelay->callback((Fl_Callback*)cb_sldrVoxDelay);
        } // Fl_Counter* sldrVoxDelay
        { btnVoxOnOff = new Fl_Light_Button(373, 310, 70, 22, _("VOX"));
          btnVoxOnOff->callback((Fl_Callback*)cb_btnVoxOnOff);
        } // Fl_Light_Button* btnVoxOnOff
        VOXtab->end();
      } // Fl_Group* VOXtab
      { SPCHtab = new Fl_Group(2, 302, 495, 50, _("Speech"));
        SPCHtab->hide();
        { MonVol = new Fl_Counter(36, 310, 70, 22, _("Mon vol"));
          MonVol->tooltip(_("Side tone volume"));
          MonVol->type(1);
          MonVol->minimum(0);
          MonVol->maximum(100);
          MonVol->step(1);
          MonVol->value(25);
        } // Fl_Counter* MonVol
        { btnSpchMon = new Fl_Light_Button(153, 310, 70, 22, _("Mon\'"));
          btnSpchMon->callback((Fl_Callback*)cb_btnSpchMon);
        } // Fl_Light_Button* btnSpchMon
        { sldrCompression = new Fl_Counter(270, 310, 70, 22, _("Comp"));
          sldrCompression->type(1);
          sldrCompression->minimum(0);
          sldrCompression->maximum(255);
          sldrCompression->step(1);
          sldrCompression->callback((Fl_Callback*)cb_sldrCompression);
        } // Fl_Counter* sldrCompression
        { btnSpchProc = new Fl_Light_Button(387, 310, 70, 22, _("Proc\'"));
          btnSpchProc->callback((Fl_Callback*)cb_btnSpchProc);
        } // Fl_Light_Button* btnSpchProc
        SPCHtab->end();
      } // Fl_Group* SPCHtab
      { RXtab = new Fl_Group(2, 302, 495, 50, _("RX"));
        RXtab->hide();
        { sldrSqlLevel = new Fl_Counter(32, 309, 80, 22, _("SQL dbm"));
          sldrSqlLevel->type(1);
          sldrSqlLevel->minimum(-127);
          sldrSqlLevel->maximum(0);
          sldrSqlLevel->step(1);
          sldrSqlLevel->value(-127);
          sldrSqlLevel->callback((Fl_Callback*)cb_sldrSqlLevel);
        } // Fl_Counter* sldrSqlLevel
        { btnSQLtype[0] = new Fl_Round_Button(155, 308, 70, 21, _("Level"));
          btnSQLtype[0]->down_box(FL_ROUND_DOWN_BOX);
          btnSQLtype[0]->value(1);
          btnSQLtype[0]->callback((Fl_Callback*)cb_btnSQLtype);
        } // Fl_Round_Button* btnSQLtype[0]
        { sldrAgcAction = new Fl_Counter(268, 309, 80, 22, _("AGC action"));
          sldrAgcAction->type(1);
          sldrAgcAction->minimum(0);
          sldrAgcAction->maximum(255);
          sldrAgcAction->step(1);
          sldrAgcAction->callback((Fl_Callback*)cb_sldrAgcAction);
        } // Fl_Counter* sldrAgcAction
        { sldrAgcSpeed = new Fl_Counter(391, 309, 80, 22, _("AGC speed"));
          sldrAgcSpeed->type(1);
          sldrAgcSpeed->minimum(0);
          sldrAgcSpeed->maximum(255);
          sldrAgcSpeed->step(1);
          sldrAgcSpeed->value(127);
          sldrAgcSpeed->callback((Fl_Callback*)cb_sldrAgcSpeed);
        } // Fl_Counter* sldrAgcSpeed
        { btnSQLtype[1] = new Fl_Round_Button(155, 329, 70, 21, _("Syllabic"));
          btnSQLtype[1]->down_box(FL_ROUND_DOWN_BOX);
          btnSQLtype[1]->callback((Fl_Callback*)cb_btnSQLtype1);
        } // Fl_Round_Button* btnSQLtype[1]
        RXtab->end();
      } // Fl_Group* RXtab
      { TXtab = new Fl_Group(2, 302, 495, 50, _("TX"));
        TXtab->hide();
        { btnAmpOnOff = new Fl_Check_Button(111, 313, 107, 15, _("Amp on/off"));
          btnAmpOnOff->down_box(FL_DOWN_BOX);
          btnAmpOnOff->callback((Fl_Callback*)cb_btnAmpOnOff);
        } // Fl_Check_Button* btnAmpOnOff
        { tuner_bypass = new Fl_Check_Button(164, 311, 70, 15, _("Tuner"));
          tuner_bypass->tooltip(_("Check to bypass tuner"));
          tuner_bypass->down_box(FL_DOWN_BOX);
          tuner_bypass->hide();
        } // Fl_Check_Button* tuner_bypass
        { sldrXmtEqualizer = new Fl_Counter(247, 307, 80, 22, _("Equilization"));
          sldrXmtEqualizer->type(1);
          sldrXmtEqualizer->minimum(-127);
          sldrXmtEqualizer->maximum(127);
          sldrXmtEqualizer->step(1);
          sldrXmtEqualizer->callback((Fl_Callback*)cb_sldrXmtEqualizer);
        } // Fl_Counter* sldrXmtEqualizer
        TXtab->end();
      } // Fl_Group* TXtab
      { OSCtab = new Fl_Group(2, 302, 495, 50, _("Osc\'"));
        OSCtab->hide();
        { ctr_vfo_adj = new Fl_Counter(191, 310, 120, 22, _("Vfo Adj(ppm)"));
          ctr_vfo_adj->callback((Fl_Callback*)cb_ctr_vfo_adj);
          ctr_vfo_adj->align(34);
        } // Fl_Counter* ctr_vfo_adj
        OSCtab->end();
      } // Fl_Group* OSCtab
      tabs->end();
    } // Fl_Tabs* tabs
    o->end();
  } // Fl_Double_Window* o
  return w;
}

Fl_Return_Button *btnOkCommsDialog=(Fl_Return_Button *)0;

static void cb_btnOkCommsDialog(Fl_Return_Button*, void*) {
  cbOkCommsDialog();
}

Fl_Choice *selectCommPort=(Fl_Choice *)0;

Fl_Double_Window* CommsDialog() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(151, 94, _("Select"));
    w = o;
    o->box(FL_UP_BOX);
    { btnOkCommsDialog = new Fl_Return_Button(20, 55, 105, 25, _("OK"));
      btnOkCommsDialog->callback((Fl_Callback*)cb_btnOkCommsDialog);
    } // Fl_Return_Button* btnOkCommsDialog
    { selectCommPort = new Fl_Choice(20, 19, 105, 21, _("tty Port:"));
      selectCommPort->down_box(FL_BORDER_BOX);
      selectCommPort->align(FL_ALIGN_TOP_LEFT);
    } // Fl_Choice* selectCommPort
    o->set_modal();
    o->end();
  } // Fl_Double_Window* o
  return w;
}

Fl_Input *txtFreqRange=(Fl_Input *)0;

Fl_Button *btnRcvAnt=(Fl_Button *)0;

static void cb_btnRcvAnt(Fl_Button*, void*) {
  if (btnRcvAnt->value() == 1) btnRcvAnt->label("B");
else btnRcvAnt->label("A");
}

Fl_Button *btnXmtAnt=(Fl_Button *)0;

static void cb_btnXmtAnt(Fl_Button*, void*) {
  if (btnXmtAnt->value() == 1) btnXmtAnt->label("B");
else btnXmtAnt->label("A");
}

Fl_Browser *brwsAntRanges=(Fl_Browser *)0;

static void cb_brwsAntRanges(Fl_Browser*, void*) {
  cbbrwsAntRanges();
}

Fl_Button *btnAddAntRange=(Fl_Button *)0;

static void cb_btnAddAntRange(Fl_Button*, void*) {
  cbAddAntRange();
}

Fl_Button *btnDeleteAntRange=(Fl_Button *)0;

static void cb_btnDeleteAntRange(Fl_Button*, void*) {
  cbDeleteAntRange();
}

Fl_Return_Button *btnAntRangeDialogOK=(Fl_Return_Button *)0;

static void cb_btnAntRangeDialogOK(Fl_Return_Button*, void*) {
  cbAntRangeDialogOK();
}

Fl_Double_Window* FreqRangesDialog() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(260, 170, _("Antenna Port Setup"));
    w = o;
    { txtFreqRange = new Fl_Input(4, 25, 75, 25);
      txtFreqRange->tooltip(_("Enter Start Freq in KHz"));
      txtFreqRange->type(2);
      txtFreqRange->textfont(13);
      txtFreqRange->align(FL_ALIGN_TOP_LEFT);
    } // Fl_Input* txtFreqRange
    { btnRcvAnt = new Fl_Button(82, 25, 30, 25, _("A"));
      btnRcvAnt->type(1);
      btnRcvAnt->down_box(FL_UP_BOX);
      btnRcvAnt->labelfont(1);
      btnRcvAnt->callback((Fl_Callback*)cb_btnRcvAnt);
    } // Fl_Button* btnRcvAnt
    { btnXmtAnt = new Fl_Button(112, 25, 30, 25, _("A"));
      btnXmtAnt->type(1);
      btnXmtAnt->down_box(FL_UP_BOX);
      btnXmtAnt->labelfont(1);
      btnXmtAnt->callback((Fl_Callback*)cb_btnXmtAnt);
    } // Fl_Button* btnXmtAnt
    { new Fl_Box(79, 5, 30, 20, _("Rcv"));
    } // Fl_Box* o
    { new Fl_Box(110, 5, 30, 20, _("Xmt"));
    } // Fl_Box* o
    { brwsAntRanges = new Fl_Browser(147, 5, 108, 160);
      brwsAntRanges->type(2);
      brwsAntRanges->labelfont(4);
      brwsAntRanges->textfont(13);
      brwsAntRanges->callback((Fl_Callback*)cb_brwsAntRanges);
    } // Fl_Browser* brwsAntRanges
    { btnAddAntRange = new Fl_Button(70, 55, 72, 25, _("Add @>|"));
      btnAddAntRange->callback((Fl_Callback*)cb_btnAddAntRange);
      btnAddAntRange->align(FL_ALIGN_RIGHT|FL_ALIGN_INSIDE);
    } // Fl_Button* btnAddAntRange
    { btnDeleteAntRange = new Fl_Button(70, 83, 72, 25, _("Delete @#2|>"));
      btnDeleteAntRange->callback((Fl_Callback*)cb_btnDeleteAntRange);
      btnDeleteAntRange->align(FL_ALIGN_RIGHT|FL_ALIGN_INSIDE);
    } // Fl_Button* btnDeleteAntRange
    { btnAntRangeDialogOK = new Fl_Return_Button(10, 135, 85, 25, _("OK"));
      btnAntRangeDialogOK->callback((Fl_Callback*)cb_btnAntRangeDialogOK);
    } // Fl_Return_Button* btnAntRangeDialogOK
    { new Fl_Box(1, 5, 75, 20, _("Freq kHz"));
    } // Fl_Box* o
    o->set_modal();
    o->end();
  } // Fl_Double_Window* o
  return w;
}

Fl_Text_Display *txtViewLog=(Fl_Text_Display *)0;

Fl_Double_Window* ViewLogDialog() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(500, 130, _("Serial Log"));
    w = o;
    { txtViewLog = new Fl_Text_Display(0, 0, 500, 130);
      txtViewLog->textfont(13);
      txtViewLog->textsize(12);
    } // Fl_Text_Display* txtViewLog
    o->end();
  } // Fl_Double_Window* o
  return w;
}

Fl_Text_Display *txtDataDisp=(Fl_Text_Display *)0;

Fl_Return_Button *btnNRAMok=(Fl_Return_Button *)0;

static void cb_btnNRAMok(Fl_Return_Button*, void*) {
  cbNRAMok();
}

Fl_Button *btnAntImpData=(Fl_Button *)0;

static void cb_btnAntImpData(Fl_Button*, void*) {
  cbNRAMAntImp();
}

Fl_Button *btnSmeterData=(Fl_Button *)0;

static void cb_btnSmeterData(Fl_Button*, void*) {
  cbNRAMsmeter();
}

Fl_Button *btnFreqRefData=(Fl_Button *)0;

static void cb_btnFreqRefData(Fl_Button*, void*) {
  cbNRAMFreqRef();
}

Fl_Button *btnPhaseDet=(Fl_Button *)0;

static void cb_btnPhaseDet(Fl_Button*, void*) {
  cbNRAMPhase();
}

Fl_Button *btnCarrierData=(Fl_Button *)0;

static void cb_btnCarrierData(Fl_Button*, void*) {
  cbNRAMCarrier();
}

Fl_Button *btnAllData=(Fl_Button *)0;

static void cb_btnAllData(Fl_Button*, void*) {
  cbNRAMAll();
}

Fl_Button *btnSaveData=(Fl_Button *)0;

static void cb_btnSaveData(Fl_Button*, void*) {
  cbNRAMSave();
}

Fl_Button *btnRestoreData=(Fl_Button *)0;

static void cb_btnRestoreData(Fl_Button*, void*) {
  cbNRAMRestore();
}

Fl_Button *btnClearData=(Fl_Button *)0;

static void cb_btnClearData(Fl_Button*, void*) {
  cbNRAMClearText();
}

Fl_Double_Window* NRAMdataDialog() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(400, 230, _("NRAM critical data"));
    w = o;
    { txtDataDisp = new Fl_Text_Display(1, 3, 395, 170);
    } // Fl_Text_Display* txtDataDisp
    { btnNRAMok = new Fl_Return_Button(319, 201, 75, 25, _("OK"));
      btnNRAMok->callback((Fl_Callback*)cb_btnNRAMok);
    } // Fl_Return_Button* btnNRAMok
    { btnAntImpData = new Fl_Button(0, 176, 60, 25, _("AntIMp"));
      btnAntImpData->callback((Fl_Callback*)cb_btnAntImpData);
    } // Fl_Button* btnAntImpData
    { btnSmeterData = new Fl_Button(60, 176, 60, 25, _("Smeter"));
      btnSmeterData->callback((Fl_Callback*)cb_btnSmeterData);
    } // Fl_Button* btnSmeterData
    { btnFreqRefData = new Fl_Button(120, 176, 60, 25, _("FreqRef"));
      btnFreqRefData->callback((Fl_Callback*)cb_btnFreqRefData);
    } // Fl_Button* btnFreqRefData
    { btnPhaseDet = new Fl_Button(0, 201, 60, 25, _("Phase"));
      btnPhaseDet->callback((Fl_Callback*)cb_btnPhaseDet);
    } // Fl_Button* btnPhaseDet
    { btnCarrierData = new Fl_Button(60, 201, 60, 25, _("Carrier"));
      btnCarrierData->callback((Fl_Callback*)cb_btnCarrierData);
    } // Fl_Button* btnCarrierData
    { btnAllData = new Fl_Button(120, 201, 60, 25, _("All"));
      btnAllData->callback((Fl_Callback*)cb_btnAllData);
    } // Fl_Button* btnAllData
    { btnSaveData = new Fl_Button(188, 201, 60, 25, _("Save"));
      btnSaveData->tooltip(_("Save to file: NRAMdata.txt"));
      btnSaveData->callback((Fl_Callback*)cb_btnSaveData);
    } // Fl_Button* btnSaveData
    { btnRestoreData = new Fl_Button(254, 200, 60, 25, _("Restore"));
      btnRestoreData->callback((Fl_Callback*)cb_btnRestoreData);
      btnRestoreData->hide();
    } // Fl_Button* btnRestoreData
    { btnClearData = new Fl_Button(188, 175, 60, 25, _("Clr Txt"));
      btnClearData->callback((Fl_Callback*)cb_btnClearData);
    } // Fl_Button* btnClearData
    o->end();
  } // Fl_Double_Window* o
  return w;
}

Fl_Counter *cntrFreqStd=(Fl_Counter *)0;

Fl_Button *btnCalibrate=(Fl_Button *)0;

static void cb_btnCalibrate(Fl_Button*, void*) {
  cbCalibrate();
}

Fl_Button *btnCalFinished=(Fl_Button *)0;

static void cb_btnCalFinished(Fl_Button*, void*) {
  cbCalFinished();
}

Fl_Double_Window* FreqCalibDialog() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(285, 62, _("Calibrate to Freq Std"));
    w = o;
    { cntrFreqStd = new Fl_Counter(15, 15, 80, 20, _("Freq. Std."));
      cntrFreqStd->minimum(5);
      cntrFreqStd->maximum(15);
      cntrFreqStd->value(10);
    } // Fl_Counter* cntrFreqStd
    { btnCalibrate = new Fl_Button(120, 15, 64, 20, _("Calibrate"));
      btnCalibrate->callback((Fl_Callback*)cb_btnCalibrate);
    } // Fl_Button* btnCalibrate
    { btnCalFinished = new Fl_Button(205, 15, 64, 20, _("Finished"));
      btnCalFinished->callback((Fl_Callback*)cb_btnCalFinished);
    } // Fl_Button* btnCalFinished
    o->end();
  } // Fl_Double_Window* o
  return w;
}

Fl_Box *lblTest=(Fl_Box *)0;

Fl_Button *prefFont=(Fl_Button *)0;

static void cb_prefFont(Fl_Button*, void*) {
  cbPrefFont();
}

Fl_Button *prefForeground=(Fl_Button *)0;

static void cb_prefForeground(Fl_Button*, void*) {
  cbPrefForeground();
}

Fl_Button *btnBacklight=(Fl_Button *)0;

static void cb_btnBacklight(Fl_Button*, void*) {
  cbBacklightColor();
}

Fl_Button *btnSmeterColor=(Fl_Button *)0;

static void cb_btnSmeterColor(Fl_Button*, void*) {
  cbSMeterColor();
}

Fl_Button *btnSWRcolor=(Fl_Button *)0;

static void cb_btnSWRcolor(Fl_Button*, void*) {
  cbSWRMeterColor();
}

Fl_Button *btnPowercolor=(Fl_Button *)0;

static void cb_btnPowercolor(Fl_Button*, void*) {
  cbPwrMeterColor();
}

Fl_Button *btnPeakColor=(Fl_Button *)0;

static void cb_btnPeakColor(Fl_Button*, void*) {
  cbPeakMeterColor();
}

Fl_Group *grpMeter1disp=(Fl_Group *)0;

Fl_Button *btnSmeterdisp=(Fl_Button *)0;

Fl_SigBar *sldrRcvSignaldisp=(Fl_SigBar *)0;

Fl_Slider *sldrSQdisp=(Fl_Slider *)0;

Fl_Box *boxSquelchdisp=(Fl_Box *)0;

Fl_Group *grpMeter2disp=(Fl_Group *)0;

Fl_Button *btnPowerdisp=(Fl_Button *)0;

Fl_SigBar *sldrFwdPwrdisp=(Fl_SigBar *)0;

Fl_Button *btnSWRdisp=(Fl_Button *)0;

Fl_SigBar *sldrRefPwrdisp=(Fl_SigBar *)0;

Fl_Choice *mnuScheme=(Fl_Choice *)0;

static void cb_mnuScheme(Fl_Choice* o, void*) {
  xcvrState.ui_scheme = o->text();
Fl::scheme(xcvrState.ui_scheme.c_str());
}

Fl_Button *pref_sys_foreground=(Fl_Button *)0;

static void cb_pref_sys_foreground(Fl_Button*, void*) {
  cb_sys_foreground();
}

Fl_Button *pref_sys_background=(Fl_Button *)0;

static void cb_pref_sys_background(Fl_Button*, void*) {
  cb_sys_background();
}

Fl_Button *prefsys_background2=(Fl_Button *)0;

static void cb_prefsys_background2(Fl_Button*, void*) {
  cb_sys_background2();
}

Fl_Button *prefsys_defaults=(Fl_Button *)0;

static void cb_prefsys_defaults(Fl_Button*, void*) {
  cb_sys_defaults();
}

Fl_Wheel_Value_Slider *sldrColors=(Fl_Wheel_Value_Slider *)0;

Fl_Button *pref_slider_background=(Fl_Button *)0;

static void cb_pref_slider_background(Fl_Button*, void*) {
  cb_slider_background();
}

Fl_Button *pref_slider_select=(Fl_Button *)0;

static void cb_pref_slider_select(Fl_Button*, void*) {
  cb_slider_select();
}

Fl_Button *prefslider_defaults=(Fl_Button *)0;

static void cb_prefslider_defaults(Fl_Button*, void*) {
  cb_slider_defaults();
}

Fl_Button *btnReset=(Fl_Button *)0;

static void cb_btnReset(Fl_Button*, void*) {
  cb_reset_display_dialog();
}

Fl_Button *btnCancel=(Fl_Button *)0;

static void cb_btnCancel(Fl_Button*, void*) {
  cbCancelDisplayDialog();
}

Fl_Return_Button *btnOkDisplayDialog=(Fl_Return_Button *)0;

static void cb_btnOkDisplayDialog(Fl_Return_Button*, void*) {
  cbOkDisplayDialog();
}

Fl_Light_Button *btn_lighted=(Fl_Light_Button *)0;

static void cb_btn_lighted(Fl_Light_Button*, void*) {
  cb_lighted_button();
}

Fl_Button *btn_lighted_default=(Fl_Button *)0;

static void cb_btn_lighted_default(Fl_Button*, void*) {
  cb_lighted_default();
}

Fl_Double_Window* DisplayDialog() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(424, 295, _("kcat colors / scheme"));
    w = o;
    { Fl_Group* o = new Fl_Group(2, 2, 218, 70);
      o->box(FL_ENGRAVED_FRAME);
      { Fl_Group* o = new Fl_Group(5, 6, 210, 35);
        o->box(FL_DOWN_BOX);
        { lblTest = new Fl_Box(7, 8, 206, 31, _("14070.000"));
          lblTest->box(FL_FLAT_BOX);
          lblTest->labelfont(4);
          lblTest->labelsize(32);
        } // Fl_Box* lblTest
        o->end();
      } // Fl_Group* o
      { prefFont = new Fl_Button(10, 46, 60, 22, _("Font"));
        prefFont->callback((Fl_Callback*)cb_prefFont);
      } // Fl_Button* prefFont
      { prefForeground = new Fl_Button(78, 46, 60, 22, _("Color"));
        prefForeground->callback((Fl_Callback*)cb_prefForeground);
      } // Fl_Button* prefForeground
      { btnBacklight = new Fl_Button(146, 46, 60, 22, _("Back"));
        btnBacklight->callback((Fl_Callback*)cb_btnBacklight);
      } // Fl_Button* btnBacklight
      o->end();
    } // Fl_Group* o
    { Fl_Group* o = new Fl_Group(2, 74, 218, 218);
      o->box(FL_ENGRAVED_BOX);
      { btnSmeterColor = new Fl_Button(154, 88, 60, 22, _("Smeter"));
        btnSmeterColor->callback((Fl_Callback*)cb_btnSmeterColor);
      } // Fl_Button* btnSmeterColor
      { btnSWRcolor = new Fl_Button(154, 144, 60, 22, _("SWR"));
        btnSWRcolor->callback((Fl_Callback*)cb_btnSWRcolor);
      } // Fl_Button* btnSWRcolor
      { btnPowercolor = new Fl_Button(154, 200, 60, 22, _("Pwr"));
        btnPowercolor->callback((Fl_Callback*)cb_btnPowercolor);
      } // Fl_Button* btnPowercolor
      { btnPeakColor = new Fl_Button(154, 256, 60, 22, _("Peak"));
        btnPeakColor->callback((Fl_Callback*)cb_btnPeakColor);
      } // Fl_Button* btnPeakColor
      { grpMeter1disp = new Fl_Group(4, 78, 65, 210);
        grpMeter1disp->box(FL_DOWN_BOX);
        grpMeter1disp->color((Fl_Color)FL_FOREGROUND_COLOR);
        grpMeter1disp->selection_color((Fl_Color)FL_LIGHT2);
        grpMeter1disp->align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
        { Fl_Button* o = btnSmeterdisp = new Fl_Button(6, 83, 40, 200);
          btnSmeterdisp->tooltip(_("Click - change scale"));
          btnSmeterdisp->box(FL_FLAT_BOX);
          btnSmeterdisp->down_box(FL_FLAT_BOX);
          btnSmeterdisp->color((Fl_Color)2);
          btnSmeterdisp->selection_color((Fl_Color)2);
          btnSmeterdisp->align(FL_ALIGN_CENTER|FL_ALIGN_INSIDE);
          o->image(image_smeter);
        } // Fl_Button* btnSmeterdisp
        { Fl_SigBar* o = sldrRcvSignaldisp = new Fl_SigBar(48, 92, 10, 182);
          sldrRcvSignaldisp->box(FL_FLAT_BOX);
          sldrRcvSignaldisp->color((Fl_Color)10);
          sldrRcvSignaldisp->selection_color((Fl_Color)2);
          sldrRcvSignaldisp->labeltype(FL_NORMAL_LABEL);
          sldrRcvSignaldisp->labelfont(0);
          sldrRcvSignaldisp->labelsize(14);
          sldrRcvSignaldisp->labelcolor((Fl_Color)FL_FOREGROUND_COLOR);
          sldrRcvSignaldisp->align(FL_ALIGN_CENTER);
          sldrRcvSignaldisp->when(FL_WHEN_RELEASE);
          o->minimum(0.0f);
          o->maximum(-128.0f);
          o->horizontal(false);
        } // Fl_SigBar* sldrRcvSignaldisp
        { sldrSQdisp = new Fl_Slider(60, 92, 8, 182);
          sldrSQdisp->box(FL_FLAT_BOX);
          sldrSQdisp->color((Fl_Color)FL_FOREGROUND_COLOR);
          sldrSQdisp->selection_color((Fl_Color)3);
          sldrSQdisp->labeltype(FL_NO_LABEL);
          sldrSQdisp->labelcolor((Fl_Color)3);
          sldrSQdisp->maximum(-127);
          sldrSQdisp->step(1);
          sldrSQdisp->value(-100);
          sldrSQdisp->deactivate();
        } // Fl_Slider* sldrSQdisp
        { boxSquelchdisp = new Fl_Box(57, 81, 9, 9);
          boxSquelchdisp->box(FL_OVAL_BOX);
          boxSquelchdisp->color((Fl_Color)6);
          boxSquelchdisp->selection_color((Fl_Color)FL_FOREGROUND_COLOR);
        } // Fl_Box* boxSquelchdisp
        grpMeter1disp->end();
      } // Fl_Group* grpMeter1disp
      { grpMeter2disp = new Fl_Group(69, 78, 80, 210);
        grpMeter2disp->box(FL_DOWN_BOX);
        grpMeter2disp->color((Fl_Color)FL_FOREGROUND_COLOR);
        grpMeter2disp->selection_color((Fl_Color)FL_LIGHT2);
        grpMeter2disp->align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
        { Fl_Button* o = btnPowerdisp = new Fl_Button(71, 83, 25, 200);
          btnPowerdisp->tooltip(_("Click - FWD / ALC"));
          btnPowerdisp->box(FL_FLAT_BOX);
          btnPowerdisp->down_box(FL_FLAT_BOX);
          btnPowerdisp->color((Fl_Color)175);
          btnPowerdisp->selection_color((Fl_Color)175);
          btnPowerdisp->align(FL_ALIGN_CENTER|FL_ALIGN_INSIDE);
          o->image(image_p150);
        } // Fl_Button* btnPowerdisp
        { Fl_SigBar* o = sldrFwdPwrdisp = new Fl_SigBar(98, 92, 10, 182);
          sldrFwdPwrdisp->box(FL_FLAT_BOX);
          sldrFwdPwrdisp->color((Fl_Color)14);
          sldrFwdPwrdisp->selection_color((Fl_Color)6);
          sldrFwdPwrdisp->labeltype(FL_NORMAL_LABEL);
          sldrFwdPwrdisp->labelfont(0);
          sldrFwdPwrdisp->labelsize(14);
          sldrFwdPwrdisp->labelcolor((Fl_Color)FL_FOREGROUND_COLOR);
          sldrFwdPwrdisp->align(FL_ALIGN_CENTER);
          sldrFwdPwrdisp->when(FL_WHEN_RELEASE);
          o->minimum(120.0f);
          o->maximum(0.0f);
          o->horizontal(false);
        } // Fl_SigBar* sldrFwdPwrdisp
        { Fl_Button* o = btnSWRdisp = new Fl_Button(122, 83, 25, 200);
          btnSWRdisp->tooltip(_("Click REF / SWR"));
          btnSWRdisp->box(FL_FLAT_BOX);
          btnSWRdisp->down_box(FL_FLAT_BOX);
          btnSWRdisp->color((Fl_Color)1);
          btnSWRdisp->selection_color((Fl_Color)1);
          btnSWRdisp->align(FL_ALIGN_CENTER|FL_ALIGN_INSIDE);
          o->image(image_swr);
        } // Fl_Button* btnSWRdisp
        { Fl_SigBar* o = sldrRefPwrdisp = new Fl_SigBar(110, 92, 10, 182);
          sldrRefPwrdisp->box(FL_FLAT_BOX);
          sldrRefPwrdisp->color((Fl_Color)9);
          sldrRefPwrdisp->selection_color((Fl_Color)1);
          sldrRefPwrdisp->labeltype(FL_NORMAL_LABEL);
          sldrRefPwrdisp->labelfont(0);
          sldrRefPwrdisp->labelsize(14);
          sldrRefPwrdisp->labelcolor((Fl_Color)FL_FOREGROUND_COLOR);
          sldrRefPwrdisp->align(FL_ALIGN_CENTER);
          sldrRefPwrdisp->when(FL_WHEN_RELEASE);
          o->minimum(50.0f);
          o->maximum(0.0f);
          o->horizontal(false);
        } // Fl_SigBar* sldrRefPwrdisp
        grpMeter2disp->end();
      } // Fl_Group* grpMeter2disp
      o->end();
    } // Fl_Group* o
    { Fl_Group* o = new Fl_Group(220, 2, 202, 70, _("System"));
      o->box(FL_ENGRAVED_FRAME);
      o->align(FL_ALIGN_TOP_LEFT|FL_ALIGN_INSIDE);
      { mnuScheme = new Fl_Choice(227, 22, 80, 22, _("UI"));
        mnuScheme->tooltip(_("Change application look and feel"));
        mnuScheme->down_box(FL_BORDER_BOX);
        mnuScheme->callback((Fl_Callback*)cb_mnuScheme);
        mnuScheme->align(FL_ALIGN_RIGHT);
        mnuScheme->add("base");
        mnuScheme->add("gtk+");
        mnuScheme->add("plastic");
        mnuScheme->value(mnuScheme->find_item(xcvrState.ui_scheme.c_str()));
      } // Fl_Choice* mnuScheme
      { pref_sys_foreground = new Fl_Button(227, 46, 60, 22, _("Fgnd"));
        pref_sys_foreground->tooltip(_("Label color"));
        pref_sys_foreground->callback((Fl_Callback*)cb_pref_sys_foreground);
      } // Fl_Button* pref_sys_foreground
      { pref_sys_background = new Fl_Button(291, 46, 60, 22, _("Bngd"));
        pref_sys_background->tooltip(_("Background - normal"));
        pref_sys_background->callback((Fl_Callback*)cb_pref_sys_background);
      } // Fl_Button* pref_sys_background
      { prefsys_background2 = new Fl_Button(356, 46, 60, 22, _("Bgnd2"));
        prefsys_background2->tooltip(_("Background - selected"));
        prefsys_background2->callback((Fl_Callback*)cb_prefsys_background2);
      } // Fl_Button* prefsys_background2
      { prefsys_defaults = new Fl_Button(356, 21, 60, 22, _("Default"));
        prefsys_defaults->tooltip(_("Background - selected"));
        prefsys_defaults->callback((Fl_Callback*)cb_prefsys_defaults);
      } // Fl_Button* prefsys_defaults
      o->end();
    } // Fl_Group* o
    { Fl_Group* o = new Fl_Group(220, 122, 202, 88);
      o->box(FL_ENGRAVED_FRAME);
      { Fl_Wheel_Value_Slider* o = sldrColors = new Fl_Wheel_Value_Slider(226, 128, 188, 20);
        sldrColors->tooltip(_("Adjust power level"));
        sldrColors->type(5);
        sldrColors->box(FL_THIN_DOWN_BOX);
        sldrColors->color((Fl_Color)FL_BACKGROUND_COLOR);
        sldrColors->selection_color((Fl_Color)FL_BACKGROUND_COLOR);
        sldrColors->labeltype(FL_NORMAL_LABEL);
        sldrColors->labelfont(0);
        sldrColors->labelsize(14);
        sldrColors->labelcolor((Fl_Color)FL_FOREGROUND_COLOR);
        sldrColors->maximum(100);
        sldrColors->step(1);
        sldrColors->value(15);
        sldrColors->textsize(12);
        sldrColors->align(FL_ALIGN_CENTER);
        sldrColors->when(FL_WHEN_CHANGED);
        o->reverse(true);
      } // Fl_Wheel_Value_Slider* sldrColors
      { pref_slider_background = new Fl_Button(226, 154, 90, 22, _("Bngd"));
        pref_slider_background->tooltip(_("Background - normal"));
        pref_slider_background->callback((Fl_Callback*)cb_pref_slider_background);
      } // Fl_Button* pref_slider_background
      { pref_slider_select = new Fl_Button(324, 154, 90, 22, _("Button"));
        pref_slider_select->tooltip(_("Background - normal"));
        pref_slider_select->callback((Fl_Callback*)cb_pref_slider_select);
      } // Fl_Button* pref_slider_select
      { prefslider_defaults = new Fl_Button(276, 183, 90, 22, _("Default"));
        prefslider_defaults->tooltip(_("Background - selected"));
        prefslider_defaults->callback((Fl_Callback*)cb_prefslider_defaults);
      } // Fl_Button* prefslider_defaults
      o->end();
    } // Fl_Group* o
    { btnReset = new Fl_Button(232, 223, 60, 22, _("Reset"));
      btnReset->tooltip(_("Restore all flrig defaults"));
      btnReset->callback((Fl_Callback*)cb_btnReset);
    } // Fl_Button* btnReset
    { btnCancel = new Fl_Button(234, 259, 60, 22, _("Cancel"));
      btnCancel->tooltip(_("Discard current changes"));
      btnCancel->callback((Fl_Callback*)cb_btnCancel);
    } // Fl_Button* btnCancel
    { btnOkDisplayDialog = new Fl_Return_Button(347, 260, 60, 22, _("OK"));
      btnOkDisplayDialog->tooltip(_("Save Current Changes"));
      btnOkDisplayDialog->callback((Fl_Callback*)cb_btnOkDisplayDialog);
    } // Fl_Return_Button* btnOkDisplayDialog
    { Fl_Group* o = new Fl_Group(220, 74, 202, 45);
      o->box(FL_ENGRAVED_FRAME);
      { btn_lighted = new Fl_Light_Button(226, 85, 90, 22, _("Lt Btn"));
        btn_lighted->callback((Fl_Callback*)cb_btn_lighted);
      } // Fl_Light_Button* btn_lighted
      { btn_lighted_default = new Fl_Button(324, 85, 90, 22, _("Default"));
        btn_lighted_default->tooltip(_("Background - selected"));
        btn_lighted_default->callback((Fl_Callback*)cb_btn_lighted_default);
      } // Fl_Button* btn_lighted_default
      o->end();
    } // Fl_Group* o
    o->end();
  } // Fl_Double_Window* o
  return w;
}
